#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
PATH=/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/:$PATH

# added by travis gem
# [ -f /Users/nehalecky/.travis/travis.sh ] && source /Users/nehalecky/.travis/travis.sh

# source SCM Breeze
# https://github.com/ndbroadbent/scm_breeze
[ -s "/Users/nehalecky/.scm_breeze/scm_breeze.sh" ] && source "/Users/nehalecky/.scm_breeze/scm_breeze.sh"

# The next line enables shell command completion for gcloud.
source '/Users/nehalecky/google-cloud-sdk/completion.zsh.inc'
# The next line updates PATH for the Google Cloud SDK.
source '/Users/nehalecky/google-cloud-sdk/path.zsh.inc'

export JAVA_HOME=$(/usr/libexec/java_home)
export JRE_HOME=$(/usr/libexec/java_home)

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Add Bombora development repos path
export BOMBORA_REPOS_PATH=$HOME/Projects/bombora/repos
source $BOMBORA_REPOS_PATH/yellow-api-keys/export-yellow-env-vars.sh
export CORAL_PATH=$BOMBORA_REPOS_PATH/coral

# Add autocomplete for pyinvoke
# source $CORAL_PATH/bin/local/invoke_autocomplete.zsh.sh
source ~/.zsh_completions.d/binvoke_autocomplete.zsh.sh

# Update path to conda base env bin
export CONDA_BIN_PATH=$HOME/miniconda3/bin
export PATH=$CONDA_BIN_PATH:$PATH


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/nehalecky/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/nehalecky/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/nehalecky/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/nehalecky/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
