#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Homebrew
eval $(/opt/homebrew/bin/brew shellenv)

## iTerm2 Shell Integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

## Dotfile Config

# Add alias for dotfile config command
alias dotfiles='git --git-dir=$HOME/.dotfiles-config/ --work-tree=$HOME'

## Secrets Management
export KEYBASE_BASE_PATH=/Volumes/Keybase
export KEYBASE_PRIVATE_PATH=$KEYBASE_BASE_PATH/private/nehalecky

# export JAVA_HOME=$(/usr/libexec/java_home)
# export JRE_HOME=$(/usr/libexec/java_home)

# fzf configs
# installed from macports, via
# sudo port install fzf
export FZF_KEY_BINDS_SCRIPT=/opt/local/share/fzf/shell/key-bindings.zsh
[ -f  $FZF_KEY_BINDS_SCRIPT ] && source $FZF_KEY_BINDS_SCRIPT
#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Google Cloud SDK setup

  # The next line updates PATH for the Google Cloud SDK.
  # if [ -f '/Users/nhalecky/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/nhalecky/google-cloud-sdk/path.zsh.inc'; fi
  # # The next line enables shell command completion for gcloud.
  # if [ -f '/Users/nhalecky/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/nhalecky/google-cloud-sdk/completion.zsh.inc'; fi


# Setup for Bombora Development

  # export BOMBORA_REPOS_PATH=$HOME/repos/bombora/
  # Bombora secrets
  # source $KEYBASE_PRIVATE_PATH/bombora/source-secrets.sh
  # source $BOMBORA_REPOS_PATH/yellow-api-keys/export-yellow-env-vars.sh
  # export CORAL_REPO_PATH=$BOMBORA_REPOS_PATH/coral

  # Add autocomplete for pyinvoke
  # source ~/.zsh_completions.d/binvoke_autocomplete.zsh.sh
