#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
PATH=/opt/local/Library/Frameworks/Python.framework/Versions/Current/bin/:$PATH

# source SCM Breeze
# https://github.com/ndbroadbent/scm_breeze
#[ -s "/Users/nehalecky/.scm_breeze/scm_breeze.sh" ] && source "/Users/nehalecky/.scm_breeze/scm_breeze.sh"

export JAVA_HOME=$(/usr/libexec/java_home)
export JRE_HOME=$(/usr/libexec/java_home)

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Add Bombora development repos path
export BOMBORA_REPOS_PATH=$HOME/repos/bombora/
# Bombora secrets
source /keybase/private/nehalecky/bombora/source-secrets.sh
# Bombora team secrets
source $BOMBORA_REPOS_PATH/yellow-api-keys/export-yellow-env-vars.sh
export CORAL_REPO_PATH=$BOMBORA_REPOS_PATH/coral

# Add autocomplete for pyinvoke
# source ~/.zsh_completions.d/binvoke_autocomplete.zsh.sh

# Update path to conda base env bin
export CONDA_BIN_PATH=/usr/local/miniconda3/bin
export PATH=$CONDA_BIN_PATH:$PATH

# fzf configs
# installed from macports, via
# sudo port install fzf
export FZF_KEY_BINDS_SCRIPT=/opt/local/share/fzf/shell/key-bindings.zsh
[ -f  $FZF_KEY_BINDS_SCRIPT ] && source $FZF_KEY_BINDS_SCRIPT
#[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/nhalecky/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/nhalecky/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/nhalecky/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/nhalecky/google-cloud-sdk/completion.zsh.inc'; fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/usr/local/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/usr/local/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/usr/local/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/usr/local/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
